export const HeaderActionTypes = {
    SWITCH_TO_HOME_PAGE: "SWITCH_TO_HOME_PAGE",
    SWITCH_TO_ABOUT_PAGE: "SWITCH_TO_ABOUT_PAGE",
    SWITCH_TO_SERVICE_PAGE: "SWITCH_TO_SERVICE_PAGE",
    SWITCH_TO_DOCTOR_PAGE: "SWITCH_TO_DOCTOR_PAGE",
    SWITCH_TO_FACILITY_PAGE: "SWITCH_TO_FACILITY_PAGE",
    SWITCH_TO_SIGNUP_PAGE: "SWITCH_TO_SIGNUP_PAGE",
    SWITCH_TO_SIGNIN_PAGE: "SWITCH_TO_SIGNIN_PAGE",
};
